/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-20 04:51:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import weview.dto.MainDto;
import java.util.List;

public final class mainpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/../inc.jsp", Long.valueOf(1642573822000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("weview.dto.MainDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"resources/assets/favicon.ico\" />\r\n");
      out.write("<!-- Bootstrap icons-->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("<link href=\"resources/css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"resources/css/customstyle.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"resources/css/font.css\" rel=\"stylesheet\" />");
      out.write("\r\n");
      out.write("\r\n");

	MainDto ranmov = (MainDto) request.getAttribute("ranmov");
	List<MainDto> obslist = (List<MainDto>) request.getAttribute("obs");
	List<MainDto> obdlist = (List<MainDto>) request.getAttribute("obd");
	List<MainDto> obrlist = (List<MainDto>) request.getAttribute("obr");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Weview - 메인</title>\r\n");
      out.write("        <style>\r\n");
      out.write("        	.ignore-atag:link, .ignore-atag:visited\r\n");
      out.write("        	{\r\n");
      out.write("        		color: white;\r\n");
      out.write("        		text-decoration: none;\r\n");
      out.write("        	}\r\n");
      out.write("        	.ignore-atag:hover\r\n");
      out.write("        	{\r\n");
      out.write("        		color: white;\r\n");
      out.write("        		text-decoration: underline;\r\n");
      out.write("        	}\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/navigation.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- Header-->\r\n");
      out.write("       \r\n");
      out.write("        <!-- Section-->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 배너 -->\r\n");

	if(ranmov != null)
	{

      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("        	<div>\r\n");
      out.write("        		<div class=\"banner-height \" id=\"banner\" \r\n");
      out.write("        		style=\"background: linear-gradient(to left,\r\n");
      out.write("						            rgba(20, 20, 20, 0) 10%,\r\n");
      out.write("						            rgba(20, 20, 20, 0.25) 25%,\r\n");
      out.write("						            rgba(20, 20, 20, 0.5) 50%,\r\n");
      out.write("						            rgba(20, 20, 20, 0.75) 75%,\r\n");
      out.write("						            rgba(20, 20, 20, 1) 100%\r\n");
      out.write("						          ), url('resources");
      out.print(ranmov.getPoster().replaceAll("\\\\", "/") );
      out.write("');\r\n");
      out.write("						background-size: contain\"> <!-- 배경 이미지 flex -->\r\n");
      out.write("					<div class=\"container banner-display\" \r\n");
      out.write("					style=\"height: inherit;\r\n");
      out.write("						   padding: 2em;\">\r\n");
      out.write("	        			<div>\r\n");
      out.write("	        				<h1 style=\"font-size: 5em;\">\r\n");
      out.write("	        				<a href=\"http://localhost:8080/weview/detailpage.do?seq_movie=");
      out.print(ranmov.getSeq_movie());
      out.write("\"\r\n");
      out.write("	        				class=\"ignore-atag\">");
      out.print(ranmov.getTitle() );
      out.write("</a>\r\n");
      out.write("	        				</h1>\r\n");
      out.write("	        			</div><!-- 제목 -->\r\n");
      out.write("	        			<div><h3>주연</h3>\r\n");
      out.write("		        			<p style=\"font-size: 1.4em;\">\r\n");
      out.write("		        				");
      out.print(ranmov.getActor().replaceAll("/", ", ") );
      out.write(" 등\r\n");
      out.write("		        			</p>\r\n");
      out.write("	        			</div><!-- 정보 -->\r\n");
      out.write("	        			<div><h3>줄거리</h3>\r\n");
      out.write("		        			<p style=\"font-size: 1.4em;\">\r\n");
      out.write("		        				");
      out.print(ranmov.getStory() );
      out.write("\r\n");
      out.write("		        			</p>\r\n");
      out.write("	        			</div><!-- 줄거리 -->\r\n");
      out.write("					</div>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("        </section>\r\n");

	}

      out.write("\r\n");
      out.write("        <!-- 배너 -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- <h1 style=\"text-align: center; color: #FF6F61\">추천 영화</h1> -->\r\n");
      out.write("        \r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("                <h4>높은 평가를 받는 영화들!</h4>\r\n");
      out.write("                <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");
      out.write("                    \r\n");
      out.write("                    <!--// 하나의 추천 항목 -->\r\n");

	if(obslist != null && obslist.size() != 0)
	{
		for(int i = 0; i < obslist.size(); i++)
		{
			MainDto dto = obslist.get(i);

      out.write("\r\n");
      out.write("                    <div class=\"col mb-5\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <!-- Product image-->\r\n");
      out.write("                            <a href=\"http://localhost:8080/weview/detailpage.do?seq_movie=");
      out.print(dto.getSeq_movie());
      out.write("\">\r\n");
      out.write("                            	<img class=\"card-img-top\" src=\"resources");
      out.print(dto.getPoster() );
      out.write("\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Product details-->\r\n");
      out.write("                            <div class=\"card-body p-4\">\r\n");
      out.write("                                <div class=\"text-center\">\r\n");
      out.write("                                    <!-- Product name-->\r\n");
      out.write("                                    <h5 class=\"fw-bolder\">");
      out.print(dto.getTitle() );
      out.write("</h5>\r\n");
      out.write("                                    <p>");
      out.print(dto.getCreated().substring(0, 4) );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getCountry() );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getGenre() );
      out.write("</p>\r\n");
      out.write("                                    <div class=\"d-flex justify-content-center small text-warning mb-2\">\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p style=\"font-size: 15px;\">평균 ");
      out.print(dto.getRate() );
      out.write("</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Product actions-->\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 하나의 추천 항목 //-->\r\n");

		}
	}

      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("                <h4>최신 영화 모음집!</h4>\r\n");
      out.write("              <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");

	if(obdlist != null && obdlist.size() != 0)
	{
		for(int i = 0; i < obdlist.size(); i++)
		{
			MainDto dto = obdlist.get(i);

      out.write("\r\n");
      out.write("                    <div class=\"col mb-5\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <!-- Product image-->\r\n");
      out.write("                            <a href=\"http://localhost:8080/weview/detailpage.do?seq_movie=");
      out.print(dto.getSeq_movie());
      out.write("\">\r\n");
      out.write("                            	<img class=\"card-img-top\" src=\"resources");
      out.print(dto.getPoster() );
      out.write("\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Product details-->\r\n");
      out.write("                            <div class=\"card-body p-4\">\r\n");
      out.write("                                <div class=\"text-center\">\r\n");
      out.write("                                    <!-- Product name-->\r\n");
      out.write("                                    <h5 class=\"fw-bolder\">");
      out.print(dto.getTitle() );
      out.write("</h5>\r\n");
      out.write("                                    <p>");
      out.print(dto.getCreated().substring(0, 4) );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getCountry() );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getGenre() );
      out.write("</p>\r\n");
      out.write("                                    <div class=\"d-flex justify-content-center small text-warning mb-2\">\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p style=\"font-size: 15px;\">평균 ");
      out.print(dto.getRate() );
      out.write("</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Product actions-->\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 하나의 추천 항목 //-->\r\n");

		}
	}

      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("             <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("                <h4>긴 런닝타임의 영화가 보고 싶다면!</h4>\r\n");
      out.write("              <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">\r\n");

	if(obrlist != null && obrlist.size() != 0)
	{
		for(int i = 0; i < obrlist.size(); i++)
		{
			MainDto dto = obrlist.get(i);

      out.write("\r\n");
      out.write("                    <div class=\"col mb-5\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <!-- Product image-->\r\n");
      out.write("                            <a href=\"http://localhost:8080/weview/detailpage.do?seq_movie=");
      out.print(dto.getSeq_movie());
      out.write("\">\r\n");
      out.write("                            	<img class=\"card-img-top\" src=\"resources");
      out.print(dto.getPoster() );
      out.write("\" alt=\"...\" />\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Product details-->\r\n");
      out.write("                            <div class=\"card-body p-4\">\r\n");
      out.write("                                <div class=\"text-center\">\r\n");
      out.write("                                    <!-- Product name-->\r\n");
      out.write("                                    <h5 class=\"fw-bolder\">");
      out.print(dto.getTitle() );
      out.write("</h5>\r\n");
      out.write("                                    <p>");
      out.print(dto.getCreated().substring(0, 4) );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getCountry() );
      out.write(' ');
      out.write('·');
      out.write(' ');
      out.print(dto.getGenre() );
      out.write("</p>\r\n");
      out.write("                                    <div class=\"d-flex justify-content-center small text-warning mb-2\">\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                        <div class=\"bi-star-fill\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p style=\"font-size: 15px;\">평균 ");
      out.print(dto.getRate() );
      out.write("</p>\r\n");
      out.write("                                    <p style=\"font-size: 17px; font-weight: bold; color: red;\">");
      out.print(dto.getRunningtime() );
      out.write("분</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Product actions-->\r\n");
      out.write("                          \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 하나의 추천 항목 //-->\r\n");

		}
	}

      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
