/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-20 02:31:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic+Coding|Noto+Sans+KR&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 55px 0 35px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("	margin-left: 15%;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 55px 0 35px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub:hover {\r\n");
      out.write("	background-color: #316aff;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sub {\r\n");
      out.write("	border: 2px solid #316aff;\r\n");
      out.write("	border-radius: 50px;\r\n");
      out.write("	padding: 10px 70px;\r\n");
      out.write("	text-decoration: inherit;\r\n");
      out.write("	font-weight: 30;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #316aff;\r\n");
      out.write("	-webkit-transition-duration: 200ms;\r\n");
      out.write("	transition-duration: 200ms;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta {\r\n");
      out.write("	border-top: 2px solid #999999;\r\n");
      out.write("	border-bottom: 2px solid #999999;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta th, .ta td {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	border-top: 1px solid #cccccc;\r\n");
      out.write("	border-left: 1px solid #cccccc;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta th:first-child {\r\n");
      out.write("	border-left: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta tr:first-child th {\r\n");
      out.write("	border-top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta tr:first-child td {\r\n");
      out.write("	border-top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta th {\r\n");
      out.write("	padding: 10px 10px 10px 55px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #222222;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ta td {\r\n");
      out.write("	padding: 10px 55px;\r\n");
      out.write("	color: #777777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ab {\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #373737;\r\n");
      out.write("	border: 1px solid #cccccc;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	transition: all 0.5s;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	line-height: 38px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tel {\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #373737;\r\n");
      out.write("	border: 1px solid #cccccc;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	transition: all 0.5s;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	line-height: 38px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".m {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bo {\r\n");
      out.write("	width: 60px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("	width: 90px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ap {\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	margin: 0 10px 0 10px;\r\n");
      out.write("	border: 1px solid rgb(190, 186, 186);\r\n");
      out.write("	background-color: #dddcdc;\r\n");
      out.write("	border-radius: 50px;\r\n");
      out.write("	padding: 2px 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bb {\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #373737;\r\n");
      out.write("	border: 1px solid #cccccc;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	transition: all 0.5s;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	line-height: 38px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ac {\r\n");
      out.write("	padding: 0 20px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #373737;\r\n");
      out.write("	border: 1px solid #cccccc;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	transition: all 0.5s;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	line-height: 38px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".app {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".re {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	border: 2px solid gray;\r\n");
      out.write("	padding: 5px 20px;\r\n");
      out.write("	border-radius: 50px;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".h4 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	margin-left: 800px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<h1>회원가입</h1>\r\n");
      out.write("	<h3 class=\"h3\">입력사항</h3>\r\n");
      out.write("	<form id=\"frm\" action=\"regiAf.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<table class=\"ta\">\r\n");
      out.write("			<caption></caption>\r\n");
      out.write("			<colgroup>\r\n");
      out.write("				<col style=\"width: 200px;\">\r\n");
      out.write("				<col>\r\n");
      out.write("			</colgroup>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>아이디</th>\r\n");
      out.write("					<td><input type=\"text\" class=\"ab\" name=\"id\" id=\"id\"\r\n");
      out.write("						style=\"width: 150px\"> <span class=\"ap\"><a href=\"#\"\r\n");
      out.write("							id=\"btn\" class=\"app\">아이디 중복</a></span><span class=\"info\">아이디 입력 후\r\n");
      out.write("							<strong>'아이디 중복확인'</strong> 버튼을 클릭해주세요\r\n");
      out.write("					</span> <br>\r\n");
      out.write("						<p id=\"idcheck\" style=\"font-size: 12px; margin-top: 10px\"></p></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>패스워드</th>\r\n");
      out.write("					<td><input type=\"password\" class=\"ac\" name=\"pwd\" id=\"pwd\"\r\n");
      out.write("						style=\"width: 150px;\"><span class=\"info\">비밀번호는\r\n");
      out.write("							4~10자리로 입력해주시기 바랍니다.</span></td>\r\n");
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"name\" id=\"name\" class=\"ab\"\r\n");
      out.write("						style=\"width: 150px;\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이메일</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"email\" id=\"email\" class=\"ab\"\r\n");
      out.write("						style=\"width: 150px;\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>닉네임</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"nickname\" id=\"nickname\"\r\n");
      out.write("						class=\"ab\" style=\"width: 150px;\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>프로필</th>\r\n");
      out.write("					<td><div class=\"select_img\">\r\n");
      out.write("							<img src=\"\" /> <input type=\"file\" id=\"gdsImg\" name=\"file\" />\r\n");
      out.write("						</div>");
      out.print(request.getRealPath("/") );
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		<h4 class=\"h4\">\r\n");
      out.write("			<a href=\"login.do\" class=\"re\">돌아가기</a>\r\n");
      out.write("		</h4>\r\n");
      out.write("		<h3 id=\"btn1\">\r\n");
      out.write("			<button type=\"button\" onclick=\"account()\" id=\"sub\">가입하기</button>\r\n");
      out.write("		</h3>\r\n");
      out.write("	</form>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\"#gdsImg\").change(\r\n");
      out.write("				function() {\r\n");
      out.write("					if (this.files && this.files[0]) {\r\n");
      out.write("						var reader = new FileReader;\r\n");
      out.write("						reader.onload = function(data) {\r\n");
      out.write("							$(\".select_img img\")\r\n");
      out.write("									.attr(\"src\", data.target.result).width(180)\r\n");
      out.write("									.height(180);\r\n");
      out.write("						}\r\n");
      out.write("						reader.readAsDataURL(this.files[0]);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("			$(\"#btn\").click(function() {\r\n");
      out.write("				//	alert('btn click');\r\n");
      out.write("				//	let id = $(\"#id\").val();\r\n");
      out.write("				//	alert(id);\r\n");
      out.write("\r\n");
      out.write("				// id 확인 -> ajax\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"idcheck.do\",\r\n");
      out.write("					type : \"post\",\r\n");
      out.write("					data : {\r\n");
      out.write("						id : $(\"#id\").val()\r\n");
      out.write("					},\r\n");
      out.write("					success : function(msg) {\r\n");
      out.write("						//	alert('success');\r\n");
      out.write("						//	alert(msg);\r\n");
      out.write("\r\n");
      out.write("						if (msg == \"YES\") {\r\n");
      out.write("							$(\"#idcheck\").css(\"color\", \"#0000ff\");\r\n");
      out.write("							$(\"#idcheck\").html(\"사용할 수 있는 아이디입니다\");\r\n");
      out.write("						} else {\r\n");
      out.write("							$(\"#idcheck\").css(\"color\", \"#ff0000\");\r\n");
      out.write("							$(\"#idcheck\").html(\"사용 중인 아이디입니다\");\r\n");
      out.write("							$(\"#id\").val(\"\");\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function() {\r\n");
      out.write("						alert('error');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function account() {\r\n");
      out.write("			//	alert('account');\r\n");
      out.write("\r\n");
      out.write("			if ($(\"#id\").val() == '') {\r\n");
      out.write("				alert('아이디를 입력해 주십시오');\r\n");
      out.write("			} else if ($(\"#pwd\").val() == '') {\r\n");
      out.write("				alert('패스워드를 입력해 주십시오');\r\n");
      out.write("			} else if ($(\"#name\").val() == '') {\r\n");
      out.write("				alert('이름를 입력해 주십시오');\r\n");
      out.write("			} else if ($(\"#email\").val() == '') {\r\n");
      out.write("				alert('이메일을 입력해 주십시오');\r\n");
      out.write("			} else if ($(\"#nickname\").val() == '') {\r\n");
      out.write("				alert('닉네임을 입력해 주십시오');\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\"#frm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
